### ISSUE TITLE
SASS 与 Less 语法的比较

### ISSUE THREAD

**Issue by Calerme** [Calerme/blog#18]
Sass 与 Less 同为 CSS 预处理语言，不过作为为同一目的出现的语言，几乎提供完全相同的功能，在语法上也只是有略微的差别，本文对两门语言的语法进行对比，加深对它们的记忆。

两门语言都对 CSS 进行了以下方面的扩展，本文也以这些扩展语法展开对比：

* 变量
* 嵌套
* mixin
* extend
* 模块化
* 循环

# 变量

Sass:

```scss
$base-color: #f1f1f1;
html {
  color: $base-color:
}
```

Less:

```less
@base-color: #f1f1f1;
html {
  color: @base-color:
}
```

# 嵌套

Sass:

```scss
a {
  color: #333;
  &:hover {
    color: #777;
  }
}
```

Less:
```les
a {
  color: #333;
  &:hover {
    color: #777;
  }
```

# Mixin

Sass:

```scss
@mixin title ($color, $bg-color) {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space:  nowrap;
  color: $color;
  background-color: $bg-color;
}

h1 {
  @include title( #000, #fff);
}
```

Less:

```less
.title (@color, @bg-color) {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  color: @color;
  background-color: @bg-color;
}

h1 {
  .title(#000, #fff);
}
```

# extend

Sass:

```scss
.strong {
  font-weight: bold;
}
.h1, .h2, .h3 {
  @extend .strong;
  margin: 5px 0;
}
```

Less:

```less
.strong {
  font-weight: bold;
}
.h1, .h2, .h3 {
  &:extend(.strong);
  font-weight: bold;
}
```

# import

Sass:

```scss
@import 'variable`
```

Less:

```less
@import `variable`
```

# 循环

Sass:

```scss
@for $i from 1 through 12 {
  .col-#{$i} {
    flex: $i;
   margin: 5px;
  }
}
```

Less:

```less
.loop(@counter) when (@counter > 0) {
  .loop(@counter -1);
  .col-@{counter} {
    flex: @counter;
  }
}

.loop(12);
```
