### ISSUE TITLE
less 语法

### ISSUE THREAD

**Issue by Calerme** [Calerme/blog#2]
# 变量

```less
@gay-purple: #551A8B;

h1 { color: @gay-purple; }
```

## 作用域

```less
@color: red;
.container {
  @color: pink;
  background-color: @color; // will be `pink`
}
```

## 惰性赋值

less 中的变量可变在使用之后声明赋值，并且只要在同一作用域中，变量就以最后一次所赋的值为主。

```less
.container {
  color: @color; // will be `blue`
  @color: red;
  @color: blue;
}
```

这一特性，使得在开发过程中自定义第三方库变得十分容易。

```less
// library.less
@base-color: #551A8B;
@dark-color: darken(@base-color, 10%);

// customize.less
@import 'library.less'
@base-color: #f1f1f1;
```

## 插值

```less
@thems: "../../src/themes";

@import "@{thems}/tidal-wave.less"

// 属性名亦可使用插值
@property: color;

.wrapper {
  @{property}: #f1f1f1;
  background-@{property}: black;
}
```

## 使用变量引用变量名

```less
@line: "It is a line.";
@var: "line";
content: @@var; // => @line => "It is  a line."
```

# 继承

```less
nav ul:extend(.inline) { color: red; }
// 等同于
nav ul {
  &:extend(.inline);
  color: red;
}
```

## all 关键字

```less
.a { color: red }
.a.b { background: blue; }
.c.a { font-size: 2rem; }

.d:extend(.a all) {}
```

以上代码会编译为：

```css
.a, .d { color: red }
.a.b, .d.b { background: blue; }
.c.a, .c.d { font-size: 2rem; }
```

## 继承作用域

```less
@media print {
  .screenClass:extend(.selector) {}
  .selector { color: black; } // 它会被 .screen 继承
}
.selector { color: red; }
@media screen { 
  .selector { color: blue; } 
}
```

# Mixins

mixins 会将所有属性复制到引用它的样式块中，而不会像 extend 那样使用群组选择器。

```less
.text-red() { color: red; }
.section1 { .text-red; }
.section2 { .text-red; }
```

# 嵌套

## 指令嵌套

# 函数

# 注释

```less
/* 这段注释会出现在编译后的 css 文件中 */

// 这段注释只会在 .less 源码中存在
```
